version: "3.8"
services:
  fuseki:
    image: stain/jena-fuseki
    container_name: fuseki-aas
    ports:
      - "3030:3030"
    environment:
      # Web-UI-Login (kannst du auch weglassen)

      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin

      # <<< HIER wird das Dataset angelegt
      - FUSEKI_DATASET_1=aas
      # optionaler Typ, je nach Image-Version
      # - FUSEKI_DATASET_1_TYPE=tdb2
      # read/write erlauben
      # - FUSEKI_DATASET_1_RW=true